
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hari Shanker
 */
public class checkinpage extends javax.swing.JFrame {

    /**
     * Creates new form checkinpage
     */
    public checkinpage() {
        initComponents();
    }

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcheckinno = new javax.swing.JTextField();
        txtadults = new javax.swing.JTextField();
        txtstayingdays = new javax.swing.JTextField();
        txtchild = new javax.swing.JTextField();
        txtcheckintime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcheckindate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtidentity = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcheckinno.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcheckinno.setForeground(new java.awt.Color(204, 204, 204));
        txtcheckinno.setText("click here");
        txtcheckinno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcheckinnoMouseClicked(evt);
            }
        });
        getContentPane().add(txtcheckinno, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 153, 272, 37));

        txtadults.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtadults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtadultsMouseClicked(evt);
            }
        });
        txtadults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadultsActionPerformed(evt);
            }
        });
        getContentPane().add(txtadults, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 381, 272, 37));

        txtstayingdays.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtstayingdays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtstayingdaysMouseClicked(evt);
            }
        });
        getContentPane().add(txtstayingdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 272, 37));

        txtchild.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtchild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtchildMouseClicked(evt);
            }
        });
        getContentPane().add(txtchild, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 475, 272, 37));

        txtcheckintime.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcheckintime.setForeground(new java.awt.Color(204, 204, 204));
        txtcheckintime.setText("click here");
        txtcheckintime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcheckintimeMouseClicked(evt);
            }
        });
        txtcheckintime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckintimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcheckintime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 273, 244, 37));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Check-In No :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Staying Days :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 37));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("No Of Adults :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("No Of Childs :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 484, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Check-In Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 159, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("Check-In Time :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 277, -1, -1));

        txtcheckindate.setDateFormatString("yyyy-MM-d");
        txtcheckindate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(txtcheckindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 244, 37));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel8.setText("Check IN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 13, 233, 57));

        txtidentity.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtidentity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aadhaar Card", "Driving Licence", "Voter ID Card" }));
        getContentPane().add(txtidentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 419, 244, 38));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setText("Identity :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 429, 96, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Check IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 599, 202, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 599, 188, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/checkin.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1081, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


String time;
    private void txtadultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadultsActionPerformed

    private void txtcheckinnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcheckinnoMouseClicked
        // TODO add your handling code here:
       txtcheckinno.setText(" ");
        txtcheckinno.setForeground(Color.BLACK);
        
        try
       {
           Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
       Statement stmt=con.createStatement();
       
       String qry="select count(*)from customerentry";
       ResultSet rs=stmt.executeQuery(qry);
       if(rs.next())
       {
        int count=rs.getInt(1);
        //count=count+1;
        txtcheckinno.setText(count+"");
       
       }
       }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(this, ex);
       }
        
    }//GEN-LAST:event_txtcheckinnoMouseClicked

    private void txtcheckintimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcheckintimeMouseClicked
        // TODO add your handling code here:
         txtcheckintime.setText(" ");
        txtcheckintime.setForeground(Color.BLACK);
         try
       {
           Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
       Statement stmt=con.createStatement();
       
       String qry="select now()";
       ResultSet rs=stmt.executeQuery(qry);
     
       
       if(rs.next())
       {
        String datetime=rs.getString(1);
        time=datetime.substring(10);
    txtcheckintime.setText(time);
          
       }
       }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(this, ex);
       }
        
    }//GEN-LAST:event_txtcheckintimeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtadults.setText("");
        txtcheckinno.setText("");
        txtcheckintime.setText("");
        txtchild.setText("");
        txtstayingdays.setText("");
        txtcheckindate.setDate(new Date());
        txtidentity.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        try
        {
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
            Statement stmt=con.createStatement();
          
       // int totalmembers,stayingdays,checkinno,adults,child;
       
         int adults=Integer.parseInt(txtadults.getText());
        int  child=Integer.parseInt(txtchild.getText());
        int  totalmembers=adults+child;
     String   stayingdays=txtstayingdays.getText();
        
           String dateStr=txtcheckindate.getDate().toString();
            SimpleDateFormat formatter = new SimpleDateFormat("E MMM dd HH:mm:ss Z yyyy");
            Date date = (Date)formatter.parse(dateStr);  

            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            String checkdate =  cal.get(Calendar.YEAR) +  "/" + (cal.get(Calendar.MONTH) + 1) + "/" + cal.get(Calendar.DATE);
       
             String checkintime=txtcheckintime.getText();
              String identity=txtidentity.getSelectedItem().toString();
         int   count1=Integer.parseInt(txtcheckinno.getText());
            String qry="insert into checkin values('"+count1+"','"+count1+"','"+stayingdays+"','"+totalmembers+"','"+checkdate+"','"+time+"','"+identity+"')";
            stmt.executeUpdate(qry);
             JOptionPane.showMessageDialog(this,"Check In Successfully");
             
         new customerentry().show();
             this.dispose();
            
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this , ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcheckintimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckintimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckintimeActionPerformed

    private void txtstayingdaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtstayingdaysMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtstayingdaysMouseClicked

    private void txtadultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtadultsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtadultsMouseClicked

    private void txtchildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtchildMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtchildMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkinpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkinpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkinpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkinpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkinpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtadults;
    private com.toedter.calendar.JDateChooser txtcheckindate;
    private javax.swing.JTextField txtcheckinno;
    private javax.swing.JTextField txtcheckintime;
    private javax.swing.JTextField txtchild;
    private javax.swing.JComboBox txtidentity;
    private javax.swing.JTextField txtstayingdays;
    // End of variables declaration//GEN-END:variables
}
