
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hari Shanker
 */
public class customerentry extends javax.swing.JFrame {

    /**
     * Creates new form customerentry
     */
    public customerentry() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtcustomername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmale = new javax.swing.JRadioButton();
        txtfemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmobileno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcountry = new javax.swing.JComboBox();
        txtstate = new javax.swing.JComboBox();
        txtcity = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcustomername.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcustomername.setForeground(new java.awt.Color(204, 204, 204));
        txtcustomername.setText("enter name ");
        txtcustomername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcustomernameMouseClicked(evt);
            }
        });
        txtcustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomernameActionPerformed(evt);
            }
        });
        txtcustomername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcustomernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 190, 248, 45));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Customer Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 198, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Gender :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 276, -1, -1));

        buttonGroup1.add(txtmale);
        txtmale.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtmale.setText("Male");
        getContentPane().add(txtmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 272, -1, -1));

        buttonGroup1.add(txtfemale);
        txtfemale.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtfemale.setText("Female");
        getContentPane().add(txtfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 272, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Address :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 531, 240, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Email ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 438, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel5.setText("Customer Entry");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 13, 348, 75));

        txtemailid.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtemailid.setForeground(new java.awt.Color(204, 204, 204));
        txtemailid.setText("enter email id");
        txtemailid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailidMouseClicked(evt);
            }
        });
        getContentPane().add(txtemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 423, 248, 43));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 120, -1, 33));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("Customer ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 143, 32));

        txtcustomerid.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcustomerid.setForeground(new java.awt.Color(204, 204, 204));
        txtcustomerid.setText("click here"); // NOI18N
        txtcustomerid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcustomerid.setHighlighter(null);
        txtcustomerid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcustomeridMouseClicked(evt);
            }
        });
        txtcustomerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomeridActionPerformed(evt);
            }
        });
        txtcustomerid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcustomeridKeyTyped(evt);
            }
        });
        getContentPane().add(txtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 115, 248, 43));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Phone no :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 27));

        txtmobileno.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtmobileno.setForeground(new java.awt.Color(204, 204, 204));
        txtmobileno.setText("enter phone no");
        txtmobileno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmobilenoMouseClicked(evt);
            }
        });
        txtmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobilenoActionPerformed(evt);
            }
        });
        txtmobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobilenoKeyTyped(evt);
            }
        });
        getContentPane().add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 342, 248, 42));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setText("Country :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 196, -1, 33));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setText("State :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("City :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 544, -1, -1));

        txtcountry.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Australia", "China", "India", "Japan", "", "" }));
        txtcountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcountryMouseClicked(evt);
            }
        });
        txtcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcountryActionPerformed(evt);
            }
        });
        getContentPane().add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 196, 230, 33));

        txtstate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        getContentPane().add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 346, 230, 37));

        txtcity.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcityMouseClicked(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        getContentPane().add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 542, 230, 33));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 709, 219, 38));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 709, 158, 38));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 710, 162, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton4.setText("Go To Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 710, -1, -1));

        txtdate.setDateFormatString("yyyy-MM-d");
        txtdate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 244, 37));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/hotel-2.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 770));

        setSize(new java.awt.Dimension(1154, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int newcount,count;
    private void txtmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobilenoActionPerformed

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
       if(txtcountry.getSelectedIndex()==2)
       {
          if(txtstate.getSelectedIndex()==0)
        {
        txtcity.removeAllItems();
        txtcity.addItem("Ahemdabad");
        txtcity.addItem("Surat");
        txtcity.addItem("Jamnagar");
        txtcity.addItem("Nadiad");
        
        }
           if(txtstate.getSelectedIndex()==1)
        {
        txtcity.removeAllItems();
        txtcity.addItem("Neemuch");
        txtcity.addItem("Indore");
         txtcity.addItem("Jabalpur");
          txtcity.addItem("Ratlam");
        
        }
            if(txtstate.getSelectedIndex()==2)
        {
        txtcity.removeAllItems();
        txtcity.addItem("Mumbai");
         txtcity.addItem("Nashik");
          txtcity.addItem("Pune");
           txtcity.addItem("Thane");
        
        }
             if(txtstate.getSelectedIndex()==3)
        {
        txtcity.removeAllItems();
        txtcity.addItem("Amritsar");
        txtcity.addItem("Patiala");
         txtcity.addItem("Jalandar");
          txtcity.addItem("Ludhiana");
        
        }
              if(txtstate.getSelectedIndex()==4)
        {
        txtcity.removeAllItems();
        txtcity.addItem("Ajmair");
        txtcity.addItem("udaipur");
        txtcity.addItem("Bhilwara");
        txtcity.addItem("Jaipur");
        
        }
       }
       if(txtcountry.getSelectedIndex()==0)
       {
        txtcity.removeAllItems();
        txtcity.addItem("None");
       }
         if(txtcountry.getSelectedIndex()==1)
       {
        txtcity.removeAllItems();
        txtcity.addItem("None");
       }
           if(txtcountry.getSelectedIndex()==3)
       {
        txtcity.removeAllItems();
        txtcity.addItem("None");
       }
    }//GEN-LAST:event_txtstateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        txtcustomername.setText(" ");
         txtcustomerid.setText(" ");
          txtaddress.setText(" ");
           txtmobileno.setText(" ");
            txtemailid.setText(" ");
            buttonGroup1.clearSelection();
            txtcountry.setSelectedIndex(0);
          txtstate.removeAllItems();
          txtcity.removeAllItems();
  txtdate.setDate(new Date ());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcountryMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtcountryMouseClicked

    private void txtcityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcityMouseClicked
        // TODO add your handling code here:
        
               
    }//GEN-LAST:event_txtcityMouseClicked

    private void txtcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcountryActionPerformed
        // TODO add your handling code here:
            if(txtcountry.getSelectedIndex()==0)
        {
        txtstate.removeAllItems();
        txtstate.addItem("None");
        
        }
        if(txtcountry.getSelectedIndex()==1)
        {
           txtstate.removeAllItems();
        txtstate.addItem("None");
        }
            if(txtcountry.getSelectedIndex()==2)
        {
           txtstate.removeAllItems();
        
    
        txtstate.addItem("Gujarat");
        txtstate.addItem("Madhya Pardesh");
        txtstate.addItem("Maharashtra");
        txtstate.addItem("Punjab");
        txtstate.addItem("Rajasthan");
        }
        
    }//GEN-LAST:event_txtcountryActionPerformed

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtcityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try
       {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
            Statement stmt=con.createStatement();
           
            int customerid=Integer.parseInt(txtcustomerid.getText());
             String customername=txtcustomername.getText();
            String mobileno=txtmobileno.getText();
            String emailid=txtemailid.getText();
          
            
            String dateStr=txtdate.getDate().toString();
            SimpleDateFormat formatter = new SimpleDateFormat("E MMM dd HH:mm:ss Z yyyy");
            Date date = (Date)formatter.parse(dateStr);  

            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            String entrydate =  cal.get(Calendar.YEAR) +  "/" + (cal.get(Calendar.MONTH) + 1) + "/" + cal.get(Calendar.DATE);
            String address=txtaddress.getText();
            
            String qry="insert into customerentry values('"+customerid+"','"+customername+"','"+mobileno+"','"+emailid+"','"+entrydate+"','"+address+"')";
            stmt.executeUpdate(qry);
            
            
            
             JOptionPane.showMessageDialog(this,"Entry Successfully");
           
        new roomdetails().show();
        this.dispose();
        }
        catch (Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex);   
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomernameActionPerformed

    private void txtcustomeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomeridActionPerformed

    private void txtmobilenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobilenoKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(ch>='0'&&ch<='9'))
        {
             evt.consume();
        
        }
    }//GEN-LAST:event_txtmobilenoKeyTyped

    private void txtcustomernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomernameKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(ch>='a'&&ch<='z'||ch>='A'&&ch<='Z'||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE))
        {
             evt.consume();
        }
    }//GEN-LAST:event_txtcustomernameKeyTyped

    private void txtcustomeridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomeridKeyTyped
        // TODO add your handling code here:
          char ch=evt.getKeyChar();
        if((ch>='0'&&ch<='9'))
        {
             evt.consume();
        
        }
    }//GEN-LAST:event_txtcustomeridKeyTyped

    private void txtcustomeridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcustomeridMouseClicked
        // TODO add your handling code here:
        txtcustomerid.setText("");
        txtcustomerid.setForeground(Color.BLACK);
         try
       {
           Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
       Statement stmt=con.createStatement();
       
       String qry="select count(*)from customerentry";
       ResultSet rs=stmt.executeQuery(qry);
       if(rs.next())
       {
        int count=rs.getInt(1);
        count=count+1;
        txtcustomerid.setText(count+"");
       
       }
       }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(this, ex);
       }
        
        
        
    }//GEN-LAST:event_txtcustomeridMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     
        new checkoutpage().show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtcustomernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcustomernameMouseClicked
        // TODO add your handling code here:
         txtcustomername.setText(" ");
        txtcustomername.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtcustomernameMouseClicked

    private void txtmobilenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmobilenoMouseClicked
        // TODO add your handling code here:
        txtmobileno.setText(" ");
        txtmobileno.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtmobilenoMouseClicked

    private void txtemailidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailidMouseClicked
        // TODO add your handling code here:
        txtemailid.setText(" ");
        txtemailid.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtemailidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JComboBox txtcity;
    private javax.swing.JComboBox txtcountry;
    public static javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtcustomername;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JRadioButton txtfemale;
    private javax.swing.JRadioButton txtmale;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JComboBox txtstate;
    // End of variables declaration//GEN-END:variables
}
