
import com.sun.jmx.snmp.BerDecoder;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hari Shanker
 */
public class roomdetails extends javax.swing.JFrame {

    /**
     * Creates new form packagepage
     */
    public roomdetails() {
        initComponents();
    }

    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtac = new javax.swing.JRadioButton();
        txtnonac = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txttotalrooms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttypesbeds = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txttyperoom = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtroomno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Room With :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 231, -1, -1));

        buttonGroup1.add(txtac);
        txtac.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtac.setText("AC");
        getContentPane().add(txtac, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 227, -1, -1));

        buttonGroup1.add(txtnonac);
        txtnonac.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtnonac.setText("Non AC");
        getContentPane().add(txtnonac, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 227, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Total Rooms :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 308, -1, -1));

        txttotalrooms.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txttotalrooms.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttotalroomsFocusGained(evt);
            }
        });
        getContentPane().add(txttotalrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 302, 243, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Type Of Beds:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 416, -1, -1));

        txttypesbeds.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txttypesbeds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Twin" }));
        getContentPane().add(txttypesbeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 413, 243, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Type Of Room :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 548, -1, -1));

        txttyperoom.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txttyperoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard", "Deluxe", "Junior Suite", "Suite" }));
        getContentPane().add(txttyperoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 544, 229, 37));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Customer ID :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 146, -1, 34));

        txtcustomerid.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcustomerid.setForeground(new java.awt.Color(204, 204, 204));
        txtcustomerid.setText("click here");
        txtcustomerid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcustomeridMouseClicked(evt);
            }
        });
        getContentPane().add(txtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 146, 244, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Book Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 640, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("Check Room Availaiblity");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 367, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel7.setText("Room Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Room No :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        txtroomno.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtroomno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtroomnoFocusGained(evt);
            }
        });
        txtroomno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtroomnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtroomnoMouseEntered(evt);
            }
        });
        txtroomno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtroomnoKeyPressed(evt);
            }
        });
        getContentPane().add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 141, 207, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/hotel-1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 740));

        setSize(new java.awt.Dimension(956, 783));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int count1,combined,roomamou;
String roomwith, typeofrooms;
    private void txtcustomeridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcustomeridMouseClicked
        // TODO add your handling code here:
       txtcustomerid.setText("");
       txtcustomerid.setForeground(Color.BLACK);
   try
       {
           Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
       Statement stmt=con.createStatement();
       
       String qry="select count(*)from customerentry";
       ResultSet rs=stmt.executeQuery(qry);
       if(rs.next())
       {
        int count=rs.getInt(1);
        
        txtcustomerid.setText(count+"");
       
       }
       }
       catch(Exception ex)
       {
       JOptionPane.showMessageDialog(this, ex);
       }
    }//GEN-LAST:event_txtcustomeridMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
        Statement stmt=con.createStatement();
       String   typeofrooms1=txttyperoom.getSelectedItem().toString();
        String qurye="select count(*) from roombooking where typesof_room='"+ typeofrooms1+"'";
            ResultSet rsesult=stmt.executeQuery(qurye);
            if(rsesult.next())
            {
                int counting=rsesult.getInt(1);
               
                if(counting<=10){
            JOptionPane.showMessageDialog(this, "Proceed Forward");
                }else
                     JOptionPane.showMessageDialog(this, "Rooms Are full ! Sorry Choose another One");
                }
                
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int roomamount=0;
        int customerid,totalrooms;
        // TODO add your handling code here:
         if(txttyperoom.getSelectedIndex()==0)
         {
         roomamount=10000;
         if(txttypesbeds.getSelectedIndex()==0)
         {
         roomamount=roomamount+5000;
         }
         if(txttypesbeds.getSelectedIndex()==1)
         {
          roomamount=roomamount+10000;
         }
         if(txttypesbeds.getSelectedIndex()==2)
         {
          roomamount=roomamount+15000;
         }
         if(txttypesbeds.getSelectedIndex()==3)
         {
          roomamount=roomamount+20000;
         }
         }
         
         
         if(txttyperoom.getSelectedIndex()==1)
         {
         roomamount=30000;
         if(txttypesbeds.getSelectedIndex()==0)
         {
         roomamount=roomamount+5000;
         }
         if(txttypesbeds.getSelectedIndex()==1)
         {
          roomamount=roomamount+10000;
         }
         if(txttypesbeds.getSelectedIndex()==2)
         {
          roomamount=roomamount+15000;
         }
         if(txttypesbeds.getSelectedIndex()==3)
         {
          roomamount=roomamount+20000;
         }
         }
         
         if(txttyperoom.getSelectedIndex()==2)
         {
         roomamount=40000;
         if(txttypesbeds.getSelectedIndex()==0)
         {
         roomamount=roomamount+5000;
         }
         if(txttypesbeds.getSelectedIndex()==1)
         {
          roomamount=roomamount+10000;
         }
         if(txttypesbeds.getSelectedIndex()==2)
         {
          roomamount=roomamount+15000;
         }
         if(txttypesbeds.getSelectedIndex()==3)
         {
          roomamount=roomamount+20000;
         }
         }
         
         
         if(txttyperoom.getSelectedIndex()==3)
         {
         roomamount=10000;
         if(txttypesbeds.getSelectedIndex()==0)
         {
         roomamount=roomamount+5000;
         }
         if(txttypesbeds.getSelectedIndex()==1)
         {
          roomamount=roomamount+10000;
         }
         if(txttypesbeds.getSelectedIndex()==2)
         {
          roomamount=roomamount+15000;
         }
         if(txttypesbeds.getSelectedIndex()==3)
         {
          roomamount=roomamount+20000;
         }
         }
         roomamou=roomamount;
         try
        {
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
        Statement stmt=con.createStatement();
        totalrooms=Integer.parseInt(txttotalrooms.getText());
        customerid=Integer.parseInt(txtcustomerid.getText());
          
        if(txtac.isSelected())
        {
        roomwith=txtac.getText();
        }
        else{
        roomwith=txtnonac.getText();
        }
        String typeofbeds=txttypesbeds.getSelectedItem().toString();
         typeofrooms=txttyperoom.getSelectedItem().toString();
      
         int roomno=Integer.parseInt(txtroomno.getText());
        String qry="insert into roombooking values('"+customerid+"','"+totalrooms+"','"+roomwith+"','"+typeofbeds+"','"+typeofrooms +"','"+roomno+"','"+roomamou+"')";
            stmt.executeUpdate(qry);
           JOptionPane.showMessageDialog(this, "Room Booked Successfully");
            
            new checkinpage().show();
            this.dispose();
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtcustomerid.setText("");
        txttotalrooms.setText("");
        txttyperoom.setSelectedIndex(0);
        txttypesbeds.setSelectedIndex(0);
       buttonGroup1.clearSelection();
       txtroomno.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtroomnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtroomnoFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtroomnoFocusGained

    private void txttotalroomsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttotalroomsFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txttotalroomsFocusGained

    private void txtroomnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtroomnoMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtroomnoMouseEntered

    private void txtroomnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtroomnoKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtroomnoKeyPressed

    private void txtroomnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtroomnoMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtroomnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton txtac;
    public static javax.swing.JTextField txtcustomerid;
    private javax.swing.JRadioButton txtnonac;
    private javax.swing.JTextField txtroomno;
    private javax.swing.JTextField txttotalrooms;
    public static javax.swing.JComboBox txttyperoom;
    public static javax.swing.JComboBox txttypesbeds;
    // End of variables declaration//GEN-END:variables
}
