
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hari Shanker
 */
public class totalbillpage extends javax.swing.JFrame {

    /**
     * Creates new form totalbillpage
     */
    public totalbillpage() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcustomername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstayingdays = new javax.swing.JTextField();
        txtmobileno = new javax.swing.JTextField();
        txttotalmembers = new javax.swing.JTextField();
        txttotalrooms = new javax.swing.JTextField();
        txtcheckindate = new javax.swing.JTextField();
        txtroomtype = new javax.swing.JTextField();
        txtbedtype = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtroomamount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnetbill = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcheckoutdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Billing ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Customer Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 101, -1, -1));

        txtcustomername.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcustomername.setForeground(new java.awt.Color(204, 204, 204));
        txtcustomername.setText("enter name");
        txtcustomername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcustomernameMouseClicked(evt);
            }
        });
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 97, 251, 37));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Mobile No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 281, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Staying Days :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 361, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Total Members :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Check-IN Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 101, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("Total Rooms :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 361, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Bed Type :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setText("Room Type :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 281, -1, -1));

        txtstayingdays.setEditable(false);
        txtstayingdays.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtstayingdays.setToolTipText("");
        getContentPane().add(txtstayingdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 357, 251, 37));

        txtmobileno.setEditable(false);
        txtmobileno.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        getContentPane().add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 277, 251, 37));

        txttotalmembers.setEditable(false);
        txttotalmembers.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txttotalmembers.setToolTipText("");
        getContentPane().add(txttotalmembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 438, 251, 37));

        txttotalrooms.setEditable(false);
        txttotalrooms.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txttotalrooms.setToolTipText("");
        getContentPane().add(txttotalrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 357, 251, 37));

        txtcheckindate.setEditable(false);
        txtcheckindate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcheckindate.setToolTipText("");
        getContentPane().add(txtcheckindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 97, 251, 37));

        txtroomtype.setEditable(false);
        txtroomtype.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtroomtype.setToolTipText("");
        getContentPane().add(txtroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 277, 251, 37));

        txtbedtype.setEditable(false);
        txtbedtype.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtbedtype.setToolTipText("");
        getContentPane().add(txtbedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 546, 251, 37));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setText("Room Amount /D:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 433, -1, -1));

        txtroomamount.setEditable(false);
        txtroomamount.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtroomamount.setToolTipText("");
        getContentPane().add(txtroomamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 438, 251, 37));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("Customer ID :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 185, -1, -1));

        txtcustomerid.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcustomerid.setForeground(new java.awt.Color(204, 204, 204));
        txtcustomerid.setText("enter id here");
        txtcustomerid.setToolTipText("");
        txtcustomerid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcustomeridMouseClicked(evt);
            }
        });
        getContentPane().add(txtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 181, 251, 37));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("Net Bill :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 550, -1, -1));

        txtnetbill.setEditable(false);
        txtnetbill.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtnetbill.setToolTipText("");
        getContentPane().add(txtnetbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 546, 251, 37));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel13.setText("Check-Out Date :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        txtcheckoutdate.setEditable(false);
        txtcheckoutdate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcheckoutdate.setToolTipText("");
        getContentPane().add(txtcheckoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 251, 37));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Calculate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 657, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 657, 172, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 657, 158, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/bill12.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        setSize(new java.awt.Dimension(1290, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int roomamount,stayingdays;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     //   JOptionPane.showInternalMessageDialog(rootPane, "thanks", "regrads", JOptionPane.INFORMATION_MESSAGE);
         try
     {
         Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
             Statement stmt=con.createStatement();
             String customername=txtcustomername.getText();
             String qry="select * from customerentry where customername='"+customername+"'";
                     
             ResultSet rs=stmt.executeQuery(qry);
             if(rs.next())
             {
            String mobileno=rs.getString(3);
            txtmobileno.setText(mobileno);
            int customerid=rs.getInt(1);
            txtcustomerid.setText(customerid+"");
             }
             else
             {             
                     JOptionPane.showMessageDialog(this, "No Record Found"); }
              Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
             Statement stmt2=con2.createStatement();
             
             int customerid1=Integer.parseInt(txtcustomerid.getText());
             String qry2="select * from checkin where customerid='"+customerid1+"'";
                      ResultSet rs2=stmt2.executeQuery(qry2);
                      if(rs2.next())
                      {
                       stayingdays=rs2.getInt(3);
                      int totalmembers=rs2.getInt(4);
                      String checkindate=rs.getDate(5).toString();
                       txtcheckindate.setText(checkindate);
                       txtstayingdays.setText(stayingdays+"");
                       txttotalmembers.setText(totalmembers+"");
                             }
                      else
             {             
                     JOptionPane.showMessageDialog(this, "No Record Found"); }
                      
                       Connection con3=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
             Statement stmt3=con3.createStatement();
                        int customerid2=Integer.parseInt(txtcustomerid.getText());
             String qry3="select * from roombooking where customerid='"+customerid2+"'";
                      ResultSet rs3=stmt3.executeQuery(qry3);
                      if(rs3.next())
                      {
                          int totalroom=rs3.getInt(2);
                      String bedtype=rs3.getString(4);
                      String roomtype=rs3.getString(5);
                       roomamount=rs3.getInt(7);
                      txttotalrooms.setText(totalroom+"");
                      txtbedtype.setText(bedtype);
                      txtroomtype.setText(roomtype);
                     txtroomamount.setText(roomamount+"");
                      
                             }
                      else{
                      JOptionPane.showMessageDialog(this, "No Record Found"); 
                      }
                      
                       Connection con4=DriverManager.getConnection("jdbc:mysql://localhost:3306/tajhotel","root","root");
             Statement stmt4=con4.createStatement();
                      int customerid3=Integer.parseInt(txtcustomerid.getText());
             String qry4="select * from checkout where customerid='"+customerid3+"'";
                      ResultSet rs4=stmt4.executeQuery(qry4);
                      if(rs4.next())
                      {
                     String checkoutdate=rs4.getDate(3).toString();
                     txtcheckoutdate.setText(checkoutdate);
                             }
                      else{
                      JOptionPane.showMessageDialog(this, "No Record Found"); 
                      }
                    
                      
                      
                      int netbill=roomamount*stayingdays;
                      txtnetbill.setText(netbill+"");
                      
                      JOptionPane.showMessageDialog(this,"Thanks Come Again !");
                      
                      
                      
                       
                       
                      
     }
     catch(Exception ex)
     {
     JOptionPane.showMessageDialog(this,ex);
     }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtbedtype.setText("");
         txtcheckindate.setText("");
          txtcheckoutdate.setText("");
           txtcustomerid.setText("");
            txtcustomername.setText("");
             txtmobileno.setText("");
              txtnetbill.setText("");
               txtroomamount.setText("");
                txtroomtype.setText("");
                 txtstayingdays.setText("");
                  txttotalmembers.setText("");
                   txttotalrooms.setText("");
                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new customerentry().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcustomernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcustomernameMouseClicked
        // TODO add your handling code here:
         txtcustomername.setText(" ");
        txtcustomername.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtcustomernameMouseClicked

    private void txtcustomeridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcustomeridMouseClicked
        // TODO add your handling code here:
         txtcustomerid.setText(" ");
        txtcustomerid.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtcustomeridMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(totalbillpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(totalbillpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(totalbillpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(totalbillpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new totalbillpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtbedtype;
    private javax.swing.JTextField txtcheckindate;
    private javax.swing.JTextField txtcheckoutdate;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtmobileno;
    public static javax.swing.JTextField txtnetbill;
    public static javax.swing.JTextField txtroomamount;
    private javax.swing.JTextField txtroomtype;
    public static javax.swing.JTextField txtstayingdays;
    private javax.swing.JTextField txttotalmembers;
    private javax.swing.JTextField txttotalrooms;
    // End of variables declaration//GEN-END:variables
}
